
dist: bionic
language: minimal
services:
  - docker
env:
  - SONAR_VERSION=7.9.4
script:
  - ./build.sh -b local -d -l -t $SONAR_VERSION -- --build-arg=SONAR_VERSION=$SONAR_VERSION
deploy:
  provider: script
  script: ./build.sh -b quay -d -l -t $SONAR_VERSION -- --build-arg=SONAR_VERSION=$SONAR_VERSION
  on:
    branch: master
